### PR TITLE
mac fix, updating examples

### PR DESCRIPTION
**Pull request by acmacalister**
The project was not building on mac, as header file being included was named incorrectly. Also a few fixes to one of the example programs as it was crashing if the flag was not provided.

### CODE REVIEW

**Comment by acmacalister** [comment]
ah, I didn't test on Linux, only OS X. I pulled out the string uppercase as on mac the ID is something like this:

```
d02316684d7b4bdb829a55496f12fc8d
```

which uppercasing causes it to fail. Maybe it would make sense to uppercase both the p.ID() and the id from the flags, so it works on both?

**Comment by roylee17** [comment]
That would be nice, could you include it in the PR?

**Comment by acmacalister** [comment]
@roylee17 updated.

**Comment by roylee17** [comment]
Cool, thanks!

**Pull request merged**
