### PR TITLE
add Getter/Setter of the service, characteristic, and descriptor.

### PR DESCRIPTION
**Pull request by shirou**
From previous [issue](https://github.com/paypal/gatt/issues/40), I found [noble](https://github.com/sandeepmistry/noble/) uses two tiny C programs to read/write HCI and L2CAP, and works on Intel Edison(kernel 3.10).
So that, I created [noblechild](https://github.com/shirou/noblechild) which provides almost same interface to paypal/gatt via noble's C programs.
Currently, noblechild can read/write attributes. But I have to make some changes to paypal/gatt.

This PR includes some setter/getter functions to use unexported variables in Server, Characteristic, and Descriptor. No other functions are changes.
Would you please merge this PR?

Thank you!

### CODE REVIEW

**Comment by roylee17** [comment]
Sorry for the late response.

In the go gatt stack, we manage at the connections at L2CAP level, and we would like exclusive control. 
This could be achieved only with the HCI USER CHANNEL, which was introduced since linux v3.14. Without it, user may feel some inconsistent issue due to both kernel and our stack try to manage the connections.

For minor changes that could help us get along with older kernels are fine. But changing API to expose more implementation might not worth it in my opinion.

Thanks,
Roy

**Comment by shirou** [comment]
Thank you for the response.

I understand and agree about you are not support without HCI USER CHANNEL kernel. So I don't include my proxy itself into this PR. I think my proxy should be independent. This PR only includes the missing piece to get interoperability with your great stack. I try to not change your code, but I couldn't. I think this PR has only minimal changes and it does not expose so much.

I know my approach is not usual and ugly. Even so, I want to support kernel 3.10 people like Intel Edison.

I would appreciate if you would think again. 

Thank you,
Shirou

**Comment by roylee17** [comment]
Though the intention was linux-specific, but the changes in this PR are pretty platform-independent.

It somewhat promotes (exposes) implementation to the API. But I think those handles are commonly presented in other BLE stack's API as well.

Thanks!

**Comment by shirou** [comment]
Thank you!!

**Pull request merged**
