### PR TITLE
initial changes for adapter abstraction

### PR DESCRIPTION
**Pull request by roylee17**
We intend to support different platforms(e.g. Mac OS), or at least make it easier if anyone is interested in working on it.

The PR is not yet for a thorough review, but trying to get some input in the early stage.
As it involves changes of file structure, the diff looks huge in the single squashed commit.
So it probably will be easier to download the branch and review it locally with editors.

I'll incorporate the input along the way, and send revisions that break the changes into smaller logical commits.

### CODE REVIEW

**Comment by josharian** [comment]
@roylee17 I'm excited about being able to support different platforms, but I'm having a hard time figuring out how to review this--it's one giant diff, and it's not clear to me exactly what it is accomplishing, how, and why. Do you think you could write a few sentences here explaining the overall approach? That'd help a lot.

**Comment by roylee17** [comment]
The two main goals are to support 

 * both roles (client and peripheral)
 * multi-platform(linux & MacOS)

Since they are correlated in higher levels, so I'd try to address them at the same time so the implementation won't be carried away to either of them too specifically. It's a long shot, so I'm intended to work on the client support for linux first (at least partially, such as scanning), but keep the API of high levels as friendly as possible to core bluetooth. So folks interested in it may join and help on it.

This revision was too rough and too far away from that. I'll try address the above comments, and send  more organized commits in the next revisions. Thanks.

**Comment by josharian** [comment]
Sounds good. Also, feel free to just write up a proposed API (with docs!) and proposed package/code structure without necessarily going to the trouble of implementing it (assuming you feel confident that you know that it *can* be implemented). That should allow quicker iterations.

**Comment by roylee17** [comment]
I pushed another #13, which reorganize the files a bit (for review and merge)

Commits here that are more recent than "Advertisement: introduce Advertisement" are still working in progress. It's still rough, but shows the idea of high-level changes though. 

We'll promote the Server to Device, which can perform both central and peripheral tasks, such as:
 * Advertise()
 * StopAdvertising()
 * Scan()
 * ...

Callbacks corresponding to Central and Peripheral tasks are grouped into centralManagerHandler and peripheralManagerHandler respectively.

Peripheral (and peripheralManagerHandler) tasks works much the same as Server use to be.

Central (centralManagerHandler) tasks as well as the "Peripheral struct" (for the scanned devices) are still work in progress. It "looks" okay so far, but I think lots of details will be ironed out along the way of implementing more central functionalities.

**Pull request closed without merging**
